import type { Plant, PlantCategory } from "@/lib/types";

/**
 * Categories follow 02-BRAND-DAHLIA.md §3 (nursery). The plant list is the seed
 * set named in 08-CONTENT-MODEL-SANITY.md §4.
 *
 * TODO: real prices and stock — placeholders pending the owner's inventory.
 * TODO: real photography — `images[].url` is undefined so placeholder art renders.
 */

export const plantCategories: PlantCategory[] = [
  {
    title: "Indoor",
    slug: "indoor",
    description: "For the corner that needs something living in it.",
  },
  {
    title: "Succulents & Cacti",
    slug: "succulents-and-cacti",
    description: "Forgiving. Ideal if you travel, or forget.",
  },
  {
    title: "Statement",
    slug: "statement",
    description: "The big ones. They change a room.",
  },
  {
    title: "Outdoor & Seasonal",
    slug: "outdoor-and-seasonal",
    description: "Balcony, terrace, and the Islamabad spring.",
  },
  {
    title: "Pots & Planters",
    slug: "pots-and-planters",
    description: "Terracotta, stoneware, and the odd oversized thing.",
  },
  {
    title: "Care & Supplies",
    slug: "care-and-supplies",
    description: "Soil, feed, tools, and honest advice.",
  },
];

export const plants: Plant[] = [
  {
    name: "Fiddle-Leaf Fig",
    slug: "fiddle-leaf-fig",
    botanicalName: "Ficus lyrata",
    categorySlug: "statement",
    price: 8500,
    light: "bright-indirect",
    water: "medium",
    difficulty: "medium",
    petFriendly: false,
    size: "Large · 120–150cm",
    careNotes: [
      "Bright, indirect light. It will sulk if you move it around.",
      "Water when the top 5cm of soil is dry — roughly weekly in summer.",
      "Dust the leaves. It breathes through them.",
    ],
    inStock: true,
    isFeatured: true,
    colorTheme: "forest",
    images: [{ alt: "Fiddle-leaf fig in a terracotta pot" }],
  },
  {
    name: "Snake Plant",
    slug: "snake-plant",
    botanicalName: "Dracaena trifasciata",
    categorySlug: "indoor",
    price: 2200,
    light: "low",
    water: "low",
    difficulty: "easy",
    petFriendly: false,
    size: "Medium · 40–60cm",
    careNotes: [
      "Survives low light, thrives in bright. Genuinely hard to kill.",
      "Water every 2–3 weeks. When in doubt, don't.",
      "Keep it out of a cold draught in winter.",
    ],
    inStock: true,
    isFeatured: true,
    colorTheme: "fern",
    images: [{ alt: "Snake plant with upright variegated leaves" }],
  },
  {
    name: "Golden Pothos",
    slug: "golden-pothos",
    botanicalName: "Epipremnum aureum",
    categorySlug: "indoor",
    price: 1400,
    light: "low",
    water: "medium",
    difficulty: "easy",
    petFriendly: false,
    size: "Trailing · 30–90cm",
    careNotes: [
      "Happy almost anywhere. Trails from a shelf, climbs a pole.",
      "Water when the top of the soil dries out.",
      "Pinch the tips to keep it full rather than leggy.",
    ],
    inStock: true,
    isFeatured: true,
    colorTheme: "moss",
    images: [{ alt: "Golden pothos trailing from a hanging pot" }],
  },
  {
    name: "Monstera",
    slug: "monstera",
    botanicalName: "Monstera deliciosa",
    categorySlug: "statement",
    price: 6500,
    light: "bright-indirect",
    water: "medium",
    difficulty: "easy",
    petFriendly: false,
    size: "Large · 90–120cm",
    careNotes: [
      "Bright, indirect light gives you the splits in the leaves.",
      "Water weekly; let it drain properly.",
      "Give it something to climb and it will get ambitious.",
    ],
    inStock: true,
    isFeatured: true,
    colorTheme: "forest",
    images: [{ alt: "Monstera deliciosa with fenestrated leaves" }],
  },
  {
    name: "Assorted Succulents",
    slug: "assorted-succulents",
    botanicalName: "Echeveria spp.",
    categorySlug: "succulents-and-cacti",
    price: 750,
    light: "full-sun",
    water: "low",
    difficulty: "easy",
    petFriendly: true,
    size: "Small · 8–15cm",
    careNotes: [
      "As much sun as you can give them.",
      "Water deeply, then leave them alone for a fortnight.",
      "Gritty soil. Wet feet are the only real danger.",
    ],
    inStock: true,
    isFeatured: false,
    colorTheme: "sage",
    images: [{ alt: "Tray of assorted small succulents" }],
  },
  {
    name: "ZZ Plant",
    slug: "zz-plant",
    botanicalName: "Zamioculcas zamiifolia",
    categorySlug: "indoor",
    price: 3200,
    light: "low",
    water: "low",
    difficulty: "easy",
    petFriendly: false,
    size: "Medium · 45–70cm",
    careNotes: [
      "The office-corner survivor. Low light is fine.",
      "Water every 2–3 weeks at most.",
      "Glossy leaves — wipe them and it looks brand new.",
    ],
    inStock: true,
    isFeatured: false,
    colorTheme: "fern",
    images: [{ alt: "ZZ plant with glossy dark green leaves" }],
  },
  {
    name: "Areca Palm",
    slug: "areca-palm",
    botanicalName: "Dypsis lutescens",
    categorySlug: "statement",
    price: 5500,
    light: "bright-indirect",
    water: "high",
    difficulty: "medium",
    petFriendly: true,
    size: "Large · 100–160cm",
    careNotes: [
      "Bright light, no harsh afternoon sun.",
      "Likes humidity and consistently damp — not soggy — soil.",
      "Brown tips usually mean the air is too dry.",
    ],
    inStock: true,
    isFeatured: false,
    colorTheme: "sage",
    images: [{ alt: "Areca palm with feathered fronds" }],
  },
  {
    name: "Peace Lily",
    slug: "peace-lily",
    botanicalName: "Spathiphyllum wallisii",
    categorySlug: "indoor",
    price: 2600,
    light: "low",
    water: "high",
    difficulty: "easy",
    petFriendly: false,
    size: "Medium · 40–60cm",
    careNotes: [
      "Tolerates low light; flowers better in bright indirect.",
      "It droops dramatically when thirsty, then forgives you completely.",
      "Keep the leaves out of direct midday sun.",
    ],
    inStock: false,
    isFeatured: false,
    colorTheme: "moss",
    images: [{ alt: "Peace lily with a white spathe flower" }],
  },
  {
    name: "Rubber Plant",
    slug: "rubber-plant",
    botanicalName: "Ficus elastica",
    categorySlug: "statement",
    price: 4800,
    light: "bright-indirect",
    water: "medium",
    difficulty: "easy",
    petFriendly: false,
    size: "Large · 80–120cm",
    careNotes: [
      "Bright indirect light keeps the burgundy tones deep.",
      "Let the top third of the soil dry between waterings.",
      "Rotate it monthly so it grows straight.",
    ],
    inStock: true,
    isFeatured: false,
    colorTheme: "forest",
    images: [{ alt: "Rubber plant with deep burgundy-green leaves" }],
  },
  {
    name: "Spider Plant",
    slug: "spider-plant",
    botanicalName: "Chlorophytum comosum",
    categorySlug: "indoor",
    price: 1200,
    light: "bright-indirect",
    water: "medium",
    difficulty: "easy",
    petFriendly: true,
    size: "Small · 25–40cm",
    careNotes: [
      "Pet-safe and generous — it makes babies you can pot on.",
      "Water when the top of the soil is dry.",
      "Brown tips are usually tap water; try filtered.",
    ],
    inStock: true,
    isFeatured: false,
    colorTheme: "moss",
    images: [{ alt: "Spider plant with arching striped leaves" }],
  },
  {
    name: "Terracotta Pot",
    slug: "terracotta-pot",
    botanicalName: "Hand-thrown, local",
    categorySlug: "pots-and-planters",
    price: 900,
    light: "full-sun",
    water: "low",
    difficulty: "easy",
    petFriendly: true,
    size: "Sizes 10–35cm",
    careNotes: [
      "Unglazed terracotta breathes — the safest pot for anyone who overwaters.",
      "Every one has a drainage hole. We check.",
    ],
    inStock: true,
    isFeatured: false,
    colorTheme: "terracotta",
    images: [{ alt: "Stack of unglazed terracotta pots" }],
  },
  {
    name: "Potting Mix & Feed",
    slug: "potting-mix-and-feed",
    botanicalName: "House blend",
    categorySlug: "care-and-supplies",
    price: 650,
    light: "low",
    water: "low",
    difficulty: "easy",
    petFriendly: true,
    size: "5kg bag",
    careNotes: [
      "Our own mix — bark, coir, perlite. Drains like it should.",
      "Feed fortnightly through spring and summer, not in winter.",
    ],
    inStock: true,
    isFeatured: false,
    colorTheme: "fern",
    images: [{ alt: "Bag of house potting mix with a scoop" }],
  },
];

export const featuredPlants = plants.filter((p) => p.isFeatured);

export function findPlant(slug: string) {
  return plants.find((p) => p.slug === slug);
}

export function plantsInCategory(slug: string) {
  return plants.filter((p) => p.categorySlug === slug);
}
